config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_votable
  
  belongs_to :user
  has_one_attached:image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    @event = Event.first
    cover_url = rails_blob_path(@event.cover, disposition: "attachment", only_path: true)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created Pin"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin was successfully updated"
    else
      render 'edit'
    end
  end
  
  def destroy
    @pin.destroy
    redirect_to root_path
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to @pin
  end

  private

    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end

    def find_pin
      @pin = Pin.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_coffee' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "Pin Board", root_path %>
        </div>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "New Pin", new_pin_path %>
            </li>
            <li>
              <%= link_to "Account", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "Sign In", new_user_session_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div class="container">
        <% flash.each do |name, msg| %>
           <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>

        <%= yield %>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@pin.errors.count, "error") %> prevented this Pin from saving</h2>
      <ul>
        <% pin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>

  <div class='form-group'>
    <% if @pin.image.attached? %>
      <%= image_tag @pin.image, style: "width: 300px; display: block " %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class='form-group'>
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>

  <div class='form-group'>
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Edit Pin</h1>
    </div>
    <div class="panel-body">
      <strong class="center">Current Image</strong>
      <br/>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= image_tag pin.image %>
      <div class="panel-body">
        <h2>
          <%= link_to pin.title, pin %>
        </h2>
        <p class="user">Submitted by <%= pin.user.email %></p>  
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>New form</h1>
    </div>
    <div class="panel-heading">
      <%= render 'form', pin: @pin %>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image %>
      </div>
      <div class="panel-body"> 
        <h1><%= @pin.title %></h1>
        <p><%= @pin.description %></p>
        <p></p>
        Submitted by
        <%= @pin.user.email %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">Submitted by <%= @pin.user.email %></p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @pin.get_upvotes.size %>
                </span>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to 'Edit', edit_pin_path, class: "btn btn-default" %>
                <%= link_to 'Delete', pin_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>